zaim_entry_day: 25
zaim_account:  "操作対象のZaim口座"
default_zaim_income_category: "収入項目カテゴリ(デフォルト)"
items:
  - payment_name: "引去項目名"
    zaim_payment:
      name: "Zaim支出項目名(メモ)"
      category: "Zaim支出カテゴリ"
      subcategory: "Zaim支出サブカテゴリ"
  - payment_name: "引去項目 2"
    zaim_income:
      name: "Zaim収入項目名(メモ) (個別)"
      category: "Zaim収入カテゴリ (個別)"
      subcategory: "Zaim収入サブカテゴリ (個別)"
    zaim_payment:
      name: "Zaim支出項目名(メモ) 2"
      category: "Zaim支出カテゴリ 2"
      subcategory: "Zaim支出サブカテゴリ 2"
